### ISSUE TITLE
Google Fonts onboarding feedback from Yanone

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/shantell-sans#114]
I’ll start by fixing these in sources, then make a build and check that the changes make it into the final fonts.

- [x] Google Fonts doesn't accept VFs with an ital axis, last I heard. Instead, you can supply two separate VFs that are split into Roman and Italic, and the API will serve either one depending on CSS settings.

- [x] The Glyphs source needs a "License URL" field: https://scripts.sil.org/OFL

- [x] The STAT table entry for the Regular is missing the Bold linkage. Not sure where to fix this. Your "add-STAT.py" contains both the flag as well as the linked value. But the designspace file contains neither. Checking the STAT table in the binary font confirms that the flag is set, but the linked value is missing.
  - [x] I’ve added style linking values to the designspace, with no change here
  - [x] I’ve taken another look at my add-STAT.py script, but I see no clear issues in syntax/spelling or other functionality
  - [x] I filed an issue with FontTools: https://github.com/fonttools/fonttools/issues/2804
  - [x] I’ll follow up and hopefully get this resolved soon.
  - [x] Complete! The check had a bit of an error. https://github.com/googlefonts/fontbakery/issues/3895#issuecomment-1240727481

- [x] The instance "Regular Italic" should be just called "Italic".

- [x] You need to remove all fvar instances that are not the standard Regular/Bold/etc plus italics, at least for a publication on Google Fonts. Those will be accessible via the STAT table, per slider UI in Indesign or per CSS values for HTML.

- [x] The STAT table name "Upright" needs to be called "Roman" instead

- [x] Weight axis default value issue: FAIL 'Light' instance has the same coordinates as the default instance; its subfamily name should be 'Regular' [code: invalid-default-instance-subfamily-nameid:265] ...I’m not sure what to make of this error message. Indeed, the default value in the designspace file is 300, but the STAT table shows 400 as default. I would go with changing the default to 400 in the designspace file and rebuild and see if the error message persists. (I'm not as versed in VF as I should be)
  - [x] This is also passing as of the fontbakery [msousa-fix-3895](https://github.com/googlefonts/fontbakery/pull/3896) branch

- [x] STAT table: You have named instances at BNCE=62.5, but no STAT table entry at that point, only 0, 50, 100. Now again, I'm no expert, but fontbakery deems this a FAIL with the following rationale: According to the OpenType spec, in a variable font, it is strongly recommended that axis value tables be included for every element of typographic subfamily names for all of the named instances defined in the 'fvar' table.

- [x] Adjusting the Bounce axis makes text break differently in Indesign, see the two attached screenshots with BNCE=0 and BNCE=36. It actually jumps back and forth when I pull the slider, which is really annoying because it obscures what is happening here technically.
  - [x] hard to replicate... may be an issue in indesign?
![image](https://user-images.githubusercontent.com/45946693/188673563-3f68ef95-ab1f-45ef-811f-994ff86d28a4.png)
![image](https://user-images.githubusercontent.com/45946693/188673619-1ed7c5af-7af8-4080-8801-b2c7efa9e59e.png)

**Comment by arrowtype** [comment]
I can’t currently replicate the Bounce axis reflow issue, so I’ve asked for clarification.

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/45946693/189217376-3c5f5821-4ad0-4c55-9bdc-305b0fef0733.png">

<img width="1882" alt="image" src="https://user-images.githubusercontent.com/45946693/189217462-b4d150c5-64ef-43f2-8207-c4af39b7d60f.png">

**Comment by yanone** [comment]
I just loaded the font into FontGoogles and played with the BNCE axis there and also couldn't find any metrics changes. Therefore, I must conclude that the changes I found were caused by Indesign, not the font. As mentioned, the metrics changed in Indesign *while* pulling the slider at odd positions, while BNCE=0 and BNCE=100 showed identical results.

Please ignore this concern going forward.

**Comment by arrowtype** [comment]
Awesome, thanks for the update!
