### ISSUE TITLE
Subfamily name discrepancy

### ISSUE THREAD

**Issue by yanone** [arrowtype/shantell-sans#118]
I checked the 1.006 fonts designated for Google Fonts again, and found this last issue remaining:

```
     FAIL 'Light' instance has the same coordinates as the                      
          default instance; its subfamily name should be 'Regular' [code:       
          invalid-default-instance-subfamily-nameid:344]                        
```

The message suggests to set name ID 17 to `Regular` and `Italic`.

However, I want to point out the following discrepancy: The axis section of the DesignSpace files in the sources folder show weight 300 to be the default, while `add-STAT.py` in the helpers folder shows the Regular (400) to be the default. 

My guess is that either one is correct, not both, and that FAIL disappears as soon as this is aligned to either one. But then again the build setup is very complicated and I'm not sure which files are even involved.

Please take another look at this.

**Comment by arrowtype** [comment]
Can I ask what version of fontbakery you ran this check with? I think this may be resolved in the latest version, via https://github.com/googlefonts/fontbakery/pull/3896

**Comment by arrowtype** [comment]
If I run `pip install -U fontbakery` and then the `check-googlefonts` checks, I no longer get this `fail`.

**Comment by yanone** [comment]
I just ran it again after updating fontbakery. Still there. Just making sure: I ran this on the fonts in `fonts/shantell_sans-for-googlefonts`

**Comment by arrowtype** [comment]
Actually, their last official release was 22 days ago. 

What if you update with:

`pip install git+https://github.com/googlefonts/fontbakery`

Yes, that is the correct directory for the fonts I intend to PR.

**Comment by yanone** [comment]
Yup, it disappeared 👍

**Comment by arrowtype** [comment]
Awesome, thanks for letting me know!
