### ISSUE TITLE
Interpolation problems in `ShantellSans-Italic[BNCE,INFM,SPAC,wght].ttf`

### ISSUE THREAD

**Issue by behdad** [arrowtype/shantell-sans#130]
Hello!

This is an automatically-generated report about possible interpolation problems in `ShantellSans-Italic[BNCE,INFM,SPAC,wght].ttf`, as found in the Google Fonts catalog.

The particular version of the font that was tested was [archive:](archive:).

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/d6edb83d4370caca83be3043e41d51d20d6b6238/reports/ShantellSans-Italic%5BBNCE%2CINFM%2CSPAC%2Cwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/d6edb83d4370caca83be3043e41d51d20d6b6238/reports/ShantellSans-Italic%5BBNCE%2CINFM%2CSPAC%2Cwght%5D.ttf.pdf).

The report follows:
```
Glyph uni20A9.001 was not compatible:
  Masters: '', 'wght=800.0':
    Contour order differs: [0, 1, 2, 3] in '', [0, 2, 1, 3] in 'wght=800.0'
    Contour 3 start point differs: 0 in '', 6 in 'wght=800.0'; reversed: False
  Masters: 'BNCE=-100.0', 'BNCE=-100.0 wght=800.0':
    Contour order differs: [0, 1, 2, 3] in 'BNCE=-100.0', [0, 2, 1, 3] in 'BNCE=-100.0 wght=800.0'
    Contour 3 start point differs: 0 in 'BNCE=-100.0', 6 in 'BNCE=-100.0 wght=800.0'; reversed: False
  Masters: 'BNCE=100.0', 'BNCE=100.0 wght=800.0':
    Contour order differs: [0, 1, 2, 3] in 'BNCE=100.0', [0, 2, 1, 3] in 'BNCE=100.0 wght=800.0'
    Contour 3 start point differs: 0 in 'BNCE=100.0', 6 in 'BNCE=100.0 wght=800.0'; reversed: False
Glyph uni20B1 was not compatible:
  Masters: '', 'wght=800.0':
    Contour 3 start point differs: 0 in '', 6 in 'wght=800.0'; reversed: False
    Contour 4 start point differs: 0 in '', 8 in 'wght=800.0'; reversed: False
  Masters: 'BNCE=-100.0', 'BNCE=-100.0 wght=800.0':
    Contour 3 start point differs: 0 in 'BNCE=-100.0', 6 in 'BNCE=-100.0 wght=800.0'; reversed: False
    Contour 4 start point differs: 0 in 'BNCE=-100.0', 8 in 'BNCE=-100.0 wght=800.0'; reversed: False
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please apologize and ignore & close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by arrowtype** [comment]
This interpolation is a genuine error, as well. Thanks!
