### ISSUE TITLE
Slashed zero for non-web use

### ISSUE THREAD

**Issue by eggjoystick** [arrowtype/shantell-sans#133]
I saw the note about using font-feature-settings to enable a slashed zero. But I'm curious if there is a way to have the slashed zero for desktop use, for example in Libreoffice Writer. Perhaps if there is a way to build the font locally with this option, could I request some instructions? 

Thanks for sharing this beautiful font with the world!

**Comment by arrowtype** [comment]
Hey @eggjoystick, good question!

It's definitely possible to activate that feature on desktop, in various ways. For most apps, you can search something like, "libreoffice OpenType features," and they should have documentation on how to activate stylistic sets.

For LibreOffice, this looks helpful:

https://help.libreoffice.org/latest/en-US/text/shared/01/font_features.html

There is also a way to "freeze" certain features into fonts, using ...

**Comment by arrowtype** [comment]
...this tool:

https://github.com/twardoch/fonttools-opentype-feature-freezer

**Comment by arrowtype** [comment]
Please give that a try and let me know how it goes. I'll close this issue for now to keep the issue tracker tidy, but I'm happy to answer further questions if you have them!

**Comment by eggjoystick** [comment]
Hi @arrowtype 

Thanks for pointing me to these resources. I've gone down the path of using opentype-feature-freezer and was able to generate a font using this command:

```
~/.local/pipx/venvs/opentype-feature-freezer/bin/pyftfeatfreeze -f 'slashed-zero' ./Shantell_Sans-Bouncy_Regular.otf Shantell0_Sans_Bouncy_Regular.otf
```

However, when I used the font within Libreoffice Writer as a test, the 0 was without a slash.

So I followed the [instructions provided by Mozilla here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/OpenType_fonts_guide#discovering_availability_of_features_in_fonts) and dropped the file Shantell_Sans-Bouncy_Regular.otf at [this site](https://wakamaifondue.com/). 

It showed a preview of the slashed zero, which is just a regular zero without a slash.

![image](https://github.com/arrowtype/shantell-sans/assets/58571795/c46afcaa-0730-4472-aff5-9c74ff033020)

I'm not sure what I'm doing wrong, but I think I've followed all the instructions correctly without success.

**Comment by eggjoystick** [comment]
I will add that I repeated the command above with `'tnum'` instead of `slashed-zero` and it worked!

**Comment by arrowtype** [comment]
Hey, glad you got it working!

I think you maybe figured it out in the end, but in your pyftfeatfreeze command, you should use the feature _tag,_ rather than the feature name. So you would want `-f 'zero'` rather than `-f 'slashed-zero'`. Or, if you were freezing in a stylistic set (like Bulgarian Cyrillic alts), you would use a format like `-f 'ss01'`.

**Comment by eggjoystick** [comment]
Thanks for the tip! 

Also wanted to share in case it is helpful for anyone - the warning below can be ignored when using opentype-feature-freeze.

```
WARNING: [applySubstitutions] Cannot remap 'zero.tnum' -> 'zero.tnum_zero' because neither has a Unicode value assigned in any of the cmap tables.
```
