### ISSUE TITLE
Ǆ, ǅ, and ǆ characters have the caron placed strangely

### ISSUE THREAD

**Issue by mhavos** [arrowtype/shantell-sans#134]
Hi, the ⟨ǆ⟩ character and the other two case variants all place the caron on the d, while the character is generally used for the (unligatured) sequence ⟨d⟩ ⟨ž⟩. The unicode decomposition of the character is defined as `0064 017E` further supporting this, and I am not aware of another usage of this character. I assume this is probably an oversight caused by not being familiar with this character?

**Comment by arrowtype** [comment]
Oof, yes, that is definitely not intended. Thank you for taking time to file this issue. I'll investigate further and fix this in a future release.

**Comment by arrowtype** [comment]
Just confirmed that this is the case:

<img width="659" alt="image" src="https://github.com/arrowtype/shantell-sans/assets/45946693/2b6fa59a-6620-44b0-9557-17370a39c6c6">

I’ll try to fit in a fix soon. Thanks again for letting me know about it, @mhavos!

**Comment by arrowtype** [comment]
Hi @mhavos, I think I’ve fixed this issue with the latest release, https://github.com/arrowtype/shantell-sans/releases/tag/1.009.

If you have a few moments, could you please download that and check whether it corrects the issue you came across?

**Comment by mhavos** [comment]
Yes, it works correctly now! Thanks.
