### ISSUE TITLE
Kerning in i/idiereisis in Light Irregular

### ISSUE THREAD

**Issue by sikeiros** [arrowtype/shantell-sans#84]
There is a positive kerning only in Light Irregular master in `i idieresis`, not to forget to check this in other masters and in Ukrainian `iukrcyr yukrcyr`

<img width="309" alt="Screenshot 2022-07-08 at 14 19 41" src="https://user-images.githubusercontent.com/16748749/177990930-4a150281-44f6-44f6-b16a-653b79877914.png">

**Comment by arrowtype** [comment]
Anya checked this, and we placed a ligature for this in both `locl` and `calt` features.
